### ISSUE TITLE
deftest not preserving metadata

### ISSUE THREAD

**Issue by AshtonKem** [cemerick/double-check#7]
Using the official test.check dependency the following test will run with ```lein test :selenium```

```clojure
(defspec ^:manual change-feature-state 1
    (prop/for-all [actions (gen/not-empty (gen/vector (state-generator)))]
                  (perform-actions actions)))
```

But in doublecheck no tests are run.

**Comment by cemerick** [comment]
Sorry for the troubles, but I've deprecated this project. Please see the notice at the top of the repo's README. This is a good thing, fundamentally. :-)
